-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.17-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for gsmf-monev
CREATE DATABASE IF NOT EXISTS `gsmf-monev` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `gsmf-monev`;

-- Dumping structure for table gsmf-monev.hutang_master
CREATE TABLE IF NOT EXISTS `hutang_master` (
  `hutprm` int(11) NOT NULL AUTO_INCREMENT,
  `hut_mst_lock` int(11) DEFAULT 0,
  `hut_mst_dt` varchar(20) DEFAULT NULL,
  `hut_mst_nobuk` varchar(20) DEFAULT NULL,
  `hut_mst_sts` varchar(20) DEFAULT NULL,
  `hut_mst_tgl` date DEFAULT NULL,
  `hut_mst_tglrnc` date DEFAULT NULL,
  `hut_mst_pst` varchar(20) DEFAULT NULL,
  `hut_mst_kel` varchar(20) DEFAULT NULL,
  `hut_mst_rek` varchar(20) DEFAULT NULL,
  `hut_mst_rnc` double DEFAULT NULL,
  `hut_mst_ttl` double DEFAULT NULL,
  `hut_mst_ket` varchar(2000) DEFAULT NULL,
  `hut_mst_dok` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`hutprm`),
  UNIQUE KEY `hut_mst_dt_hut_mst_nobuk` (`hut_mst_dt`,`hut_mst_nobuk`),
  UNIQUE KEY `hut_mst_nobuk` (`hut_mst_nobuk`),
  KEY `hut_mst_dt_hut_mst_tgl` (`hut_mst_dt`,`hut_mst_tgl`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table gsmf-monev.hutang_master: ~2 rows (approximately)
/*!40000 ALTER TABLE `hutang_master` DISABLE KEYS */;
INSERT INTO `hutang_master` (`hutprm`, `hut_mst_lock`, `hut_mst_dt`, `hut_mst_nobuk`, `hut_mst_sts`, `hut_mst_tgl`, `hut_mst_tglrnc`, `hut_mst_pst`, `hut_mst_kel`, `hut_mst_rek`, `hut_mst_rnc`, `hut_mst_ttl`, `hut_mst_ket`, `hut_mst_dok`) VALUES
	(8, 0, 'AGR', 'AGR-20210407-72239', 'TOLAK', '2021-04-07', '2021-05-01', 'GSU', 'F-01', '2121-01', 5450000, NULL, 'COBAIN INPUT PROGRAM', 'AGR-20210407-72239.docx'),
	(9, 0, 'AGR', 'AGR-20210407-48937', 'SETUJU', '2021-04-07', '2021-04-07', 'GSU', 'F-01', '2122-01', 1250000, NULL, 'COBAIN TAMBAH BIAYA RUTIN', 'AGR-20210407-48937.jpeg'),
	(10, 0, 'AGR', 'AGR-20210407-83933', 'BARU', '2021-04-07', '2021-05-31', 'GSU', 'F-01', '2121-02', 2535000, NULL, 'PROGRAM INPUT COBAIN', 'AGR-20210407-83933.docx'),
	(11, 0, 'AGR', 'AGR-20210407-27600', 'BARU', '2021-04-07', '2021-05-10', 'GSU', 'F-01', '2122-07', 250000, NULL, 'BIAYA BIAYA TEST', 'AGR-20210407-27600.jpg');
/*!40000 ALTER TABLE `hutang_master` ENABLE KEYS */;

-- Dumping structure for table gsmf-monev.info_level_1
CREATE TABLE IF NOT EXISTS `info_level_1` (
  `infoprm` int(11) NOT NULL AUTO_INCREMENT,
  `in_lv_1_dt` varchar(20) DEFAULT NULL,
  `in_lv_1_kd` varchar(20) DEFAULT NULL,
  `in_lv_1_ket` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`infoprm`) USING BTREE,
  UNIQUE KEY `in_lv_1_dt_in_lv_1_kd` (`in_lv_1_dt`,`in_lv_1_kd`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table gsmf-monev.info_level_1: ~4 rows (approximately)
/*!40000 ALTER TABLE `info_level_1` DISABLE KEYS */;
INSERT INTO `info_level_1` (`infoprm`, `in_lv_1_dt`, `in_lv_1_kd`, `in_lv_1_ket`) VALUES
	(8, 'STATUS', 'AKTIF', 'AKTIF'),
	(9, 'STATUS', 'PASIF', 'PASIF'),
	(13, 'REKENING', 'ANGGARAN', 'ANGGARAN'),
	(14, 'REKENING', 'NERACA', 'NERACA');
/*!40000 ALTER TABLE `info_level_1` ENABLE KEYS */;

-- Dumping structure for table gsmf-monev.info_level_2
CREATE TABLE IF NOT EXISTS `info_level_2` (
  `infoprm` int(11) NOT NULL AUTO_INCREMENT,
  `in_lv_1_dt` varchar(20) DEFAULT NULL,
  `in_lv_1_kd` varchar(20) DEFAULT NULL,
  `in_lv_2_kd` varchar(20) DEFAULT NULL,
  `in_lv_2_ket` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`infoprm`) USING BTREE,
  UNIQUE KEY `in_lv_1_dt_in_lv_1_kd_in_lv_2_kd` (`in_lv_1_dt`,`in_lv_1_kd`,`in_lv_2_kd`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table gsmf-monev.info_level_2: ~7 rows (approximately)
/*!40000 ALTER TABLE `info_level_2` DISABLE KEYS */;
INSERT INTO `info_level_2` (`infoprm`, `in_lv_1_dt`, `in_lv_1_kd`, `in_lv_2_kd`, `in_lv_2_ket`) VALUES
	(1, 'REKENING', 'ANGGARAN', 'ABTS-NP', 'ABTS-NP'),
	(2, 'REKENING', 'ANGGARAN', 'ABTS-P', 'ABTS-P'),
	(3, 'REKENING', 'ANGGARAN', 'ABTS-UKSP', 'ABTS-UKSP'),
	(4, 'REKENING', 'ANGGARAN', 'ABTT', 'ABTT'),
	(5, 'REKENING', 'NERACA', 'ASET', 'ASET'),
	(6, 'REKENING', 'NERACA', 'ASET BERSIH', 'ASET BERSIH'),
	(7, 'REKENING', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN');
/*!40000 ALTER TABLE `info_level_2` ENABLE KEYS */;

-- Dumping structure for table gsmf-monev.info_level_3
CREATE TABLE IF NOT EXISTS `info_level_3` (
  `infoprm` int(11) NOT NULL AUTO_INCREMENT,
  `in_lv_1_dt` varchar(20) DEFAULT NULL,
  `in_lv_1_kd` varchar(20) DEFAULT NULL,
  `in_lv_2_kd` varchar(20) DEFAULT NULL,
  `in_lv_3_kd` varchar(20) DEFAULT NULL,
  `in_lv_3_ket` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`infoprm`) USING BTREE,
  UNIQUE KEY `in_lv_1_dt_in_lv_1_kd_in_lv_2_kd_in_lv_3_kd` (`in_lv_1_dt`,`in_lv_1_kd`,`in_lv_2_kd`,`in_lv_3_kd`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

-- Dumping data for table gsmf-monev.info_level_3: ~14 rows (approximately)
/*!40000 ALTER TABLE `info_level_3` DISABLE KEYS */;
INSERT INTO `info_level_3` (`infoprm`, `in_lv_1_dt`, `in_lv_1_kd`, `in_lv_2_kd`, `in_lv_3_kd`, `in_lv_3_ket`) VALUES
	(1, 'REKENING', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'BIAYA'),
	(2, 'REKENING', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'PENDAPATAN'),
	(3, 'REKENING', 'ANGGARAN', 'ABTS-P', 'BIAYA', 'BIAYA'),
	(4, 'REKENING', 'ANGGARAN', 'ABTS-P', 'PENDAPATAN', 'PENDAPATAN'),
	(5, 'REKENING', 'ANGGARAN', 'ABTS-UKSP', 'BIAYA', 'BIAYA'),
	(6, 'REKENING', 'ANGGARAN', 'ABTS-UKSP', 'PENDAPATAN', 'PENDAPATAN'),
	(7, 'REKENING', 'ANGGARAN', 'ABTT', 'BIAYA', 'BIAYA'),
	(8, 'REKENING', 'ANGGARAN', 'ABTT', 'PENDAPATAN', 'PENDAPATAN'),
	(9, 'REKENING', 'NERACA', 'ASET', 'ASETLAIN', 'ASETLAIN'),
	(10, 'REKENING', 'NERACA', 'ASET', 'ASETLANCAR', 'ASETLANCAR'),
	(11, 'REKENING', 'NERACA', 'ASET', 'ASETTETAP', 'ASETTETAP'),
	(12, 'REKENING', 'NERACA', 'ASET BERSIH', 'TERIKATSEMENTARA', 'TERIKATSEMENTARA'),
	(13, 'REKENING', 'NERACA', 'ASET BERSIH', 'TIDAKTERIKAT', 'TIDAKTERIKAT'),
	(14, 'REKENING', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN', 'KEWAJIBAN');
/*!40000 ALTER TABLE `info_level_3` ENABLE KEYS */;

-- Dumping structure for table gsmf-monev.info_level_4
CREATE TABLE IF NOT EXISTS `info_level_4` (
  `infoprm` int(11) NOT NULL AUTO_INCREMENT,
  `in_lv_1_dt` varchar(20) DEFAULT NULL,
  `in_lv_1_kd` varchar(20) DEFAULT NULL,
  `in_lv_2_kd` varchar(20) DEFAULT NULL,
  `in_lv_3_kd` varchar(20) DEFAULT NULL,
  `in_lv_4_kd` varchar(20) DEFAULT NULL,
  `in_lv_4_ket` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`infoprm`),
  UNIQUE KEY `in_lv_1_dt_in_lv_1_kd_in_lv_2_kd_in_lv_3_kd_in_lv_4_kd` (`in_lv_1_dt`,`in_lv_1_kd`,`in_lv_2_kd`,`in_lv_3_kd`,`in_lv_4_kd`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table gsmf-monev.info_level_4: ~35 rows (approximately)
/*!40000 ALTER TABLE `info_level_4` DISABLE KEYS */;
INSERT INTO `info_level_4` (`infoprm`, `in_lv_1_dt`, `in_lv_1_kd`, `in_lv_2_kd`, `in_lv_3_kd`, `in_lv_4_kd`, `in_lv_4_ket`) VALUES
	(1, 'REKENING', 'NERACA', 'ASET', 'ASETLANCAR', 'SETARAKAS\r', 'SETARAKAS\r'),
	(2, 'REKENING', 'NERACA', 'ASET', 'ASETLANCAR', 'PIUTANG\r', 'PIUTANG\r'),
	(3, 'REKENING', 'NERACA', 'ASET', 'ASETLANCAR', 'PERSEDIAAN\r', 'PERSEDIAAN\r'),
	(4, 'REKENING', 'NERACA', 'ASET', 'ASETLANCAR', 'PERLENGKAPAN\r', 'PERLENGKAPAN\r'),
	(5, 'REKENING', 'NERACA', 'ASET', 'ASETTETAP', 'BERGERAK\r', 'BERGERAK\r'),
	(6, 'REKENING', 'NERACA', 'ASET', 'ASETTETAP', 'TIDAKBERGERAK\r', 'TIDAKBERGERAK\r'),
	(7, 'REKENING', 'NERACA', 'ASET', 'ASETLAIN', 'LAIN\r', 'LAIN\r'),
	(8, 'REKENING', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN', 'JANGKAPANJANG\r', 'JANGKAPANJANG\r'),
	(9, 'REKENING', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN', 'JANGKAPENDEK\r', 'JANGKAPENDEK\r'),
	(10, 'REKENING', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN', 'KHUSUS\r', 'KHUSUS\r'),
	(11, 'REKENING', 'NERACA', 'ASET BERSIH', 'TIDAKTERIKAT', 'TIDAKTERIKAT\r', 'TIDAKTERIKAT\r'),
	(12, 'REKENING', 'NERACA', 'ASET BERSIH', 'TERIKATSEMENTARA', 'NONPEMBANGUNAN\r', 'NONPEMBANGUNAN\r'),
	(13, 'REKENING', 'NERACA', 'ASET BERSIH', 'TERIKATSEMENTARA', 'PEMBANGUNAN\r', 'PEMBANGUNAN\r'),
	(14, 'REKENING', 'NERACA', 'ASET BERSIH', 'TERIKATSEMENTARA', 'UKSP\r', 'UKSP\r'),
	(15, 'REKENING', 'ANGGARAN', 'ABTT', 'PENDAPATAN', 'KOLEKTE\r', 'KOLEKTE\r'),
	(16, 'REKENING', 'ANGGARAN', 'ABTT', 'PENDAPATAN', 'BANTUAN\r', 'BANTUAN\r'),
	(17, 'REKENING', 'ANGGARAN', 'ABTT', 'PENDAPATAN', 'UMUM\r', 'UMUM\r'),
	(18, 'REKENING', 'ANGGARAN', 'ABTT', 'BIAYA', 'PROGRAM\r', 'PROGRAM\r'),
	(19, 'REKENING', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN\r', 'RUTIN\r'),
	(20, 'REKENING', 'ANGGARAN', 'ABTT', 'BIAYA', 'UMUM\r', 'UMUM\r'),
	(21, 'REKENING', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'KOLEKTE\r', 'KOLEKTE\r'),
	(22, 'REKENING', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'BANTUAN\r', 'BANTUAN\r'),
	(23, 'REKENING', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'UMUM\r', 'UMUM\r'),
	(24, 'REKENING', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'RUTIN\r', 'RUTIN\r'),
	(25, 'REKENING', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'UMUM\r', 'UMUM\r'),
	(26, 'REKENING', 'ANGGARAN', 'ABTS-P', 'PENDAPATAN', 'KOLEKTE\r', 'KOLEKTE\r'),
	(27, 'REKENING', 'ANGGARAN', 'ABTS-P', 'PENDAPATAN', 'BANTUAN\r', 'BANTUAN\r'),
	(28, 'REKENING', 'ANGGARAN', 'ABTS-P', 'PENDAPATAN', 'UMUM\r', 'UMUM\r'),
	(29, 'REKENING', 'ANGGARAN', 'ABTS-P', 'BIAYA', 'RUTIN\r', 'RUTIN\r'),
	(30, 'REKENING', 'ANGGARAN', 'ABTS-P', 'BIAYA', 'UMUM\r', 'UMUM\r'),
	(31, 'REKENING', 'ANGGARAN', 'ABTS-UKSP', 'PENDAPATAN', 'KOLEKTE\r', 'KOLEKTE\r'),
	(32, 'REKENING', 'ANGGARAN', 'ABTS-UKSP', 'PENDAPATAN', 'BANTUAN\r', 'BANTUAN\r'),
	(33, 'REKENING', 'ANGGARAN', 'ABTS-UKSP', 'PENDAPATAN', 'UMUM\r', 'UMUM\r'),
	(34, 'REKENING', 'ANGGARAN', 'ABTS-UKSP', 'BIAYA', 'RUTIN\r', 'RUTIN\r'),
	(35, 'REKENING', 'ANGGARAN', 'ABTS-UKSP', 'BIAYA', 'UMUM\r', 'UMUM\r');
/*!40000 ALTER TABLE `info_level_4` ENABLE KEYS */;

-- Dumping structure for table gsmf-monev.kelompok_master
CREATE TABLE IF NOT EXISTS `kelompok_master` (
  `kelprm` int(11) NOT NULL AUTO_INCREMENT,
  `kel_mst_sts` varchar(20) DEFAULT NULL,
  `kel_mst_kode` varchar(20) DEFAULT NULL,
  `kel_mst_subkode` varchar(20) DEFAULT NULL,
  `kel_mst_ket` varchar(2000) DEFAULT NULL,
  `kel_mst_subket` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`kelprm`),
  UNIQUE KEY `kel_mst_kode_kel_mst_subkode_kel_mst_sts` (`kel_mst_sts`,`kel_mst_kode`,`kel_mst_subkode`),
  UNIQUE KEY `kel_mst_subkode` (`kel_mst_subkode`)
) ENGINE=InnoDB AUTO_INCREMENT=133 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table gsmf-monev.kelompok_master: ~65 rows (approximately)
/*!40000 ALTER TABLE `kelompok_master` DISABLE KEYS */;
INSERT INTO `kelompok_master` (`kelprm`, `kel_mst_sts`, `kel_mst_kode`, `kel_mst_subkode`, `kel_mst_ket`, `kel_mst_subket`) VALUES
	(68, 'AKTIF', 'A', 'A-01', 'BIDANG LITURGI DAN PERIBADATAN', 'BIDANG LITURGI DAN PERIBADATAN'),
	(69, 'AKTIF', 'A', 'A-02', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN TATA PERAYAAN DAN PERIBADATAN'),
	(70, 'AKTIF', 'A', 'A-03', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PRODIAKON'),
	(71, 'AKTIF', 'A', 'A-04', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PUTRA-PUTRI ALTAR'),
	(72, 'AKTIF', 'A', 'A-05', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PADUAN SUARA'),
	(73, 'AKTIF', 'A', 'A-06', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN LEKTOR'),
	(74, 'AKTIF', 'A', 'A-07', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PEMAZMUR'),
	(75, 'AKTIF', 'A', 'A-08', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PEMUSIK'),
	(76, 'AKTIF', 'A', 'A-09', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN DIRIGEN'),
	(77, 'AKTIF', 'A', 'A-10', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PARAMENTA'),
	(78, 'AKTIF', 'A', 'A-11', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN TATA ALTAR'),
	(79, 'AKTIF', 'A', 'A-12', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN LITURGI DAN PERIBADATAN LAIN-LAIN'),
	(80, 'AKTIF', 'B', 'B-01', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'BIDANG PEWARTAAN DAN EVANGELISASI'),
	(81, 'AKTIF', 'B', 'B-02', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN EVANGELISASI'),
	(82, 'AKTIF', 'B', 'B-03', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN SAKRAMEN INISIASI'),
	(83, 'AKTIF', 'B', 'B-04', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN KATEKIS'),
	(84, 'AKTIF', 'B', 'B-05', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN KERASULAN KITAB SUCI'),
	(85, 'AKTIF', 'B', 'B-06', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN USIA DINI'),
	(86, 'AKTIF', 'B', 'B-07', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN ANAK'),
	(87, 'AKTIF', 'B', 'B-08', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN REMAJA'),
	(88, 'AKTIF', 'B', 'B-09', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN ORANG MUDA'),
	(89, 'AKTIF', 'B', 'B-10', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN ORANG DEWASA'),
	(90, 'AKTIF', 'B', 'B-11', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN USIA LANJUT'),
	(91, 'AKTIF', 'B', 'B-12', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PROMOSI PANGGILAN'),
	(92, 'AKTIF', 'B', 'B-13', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN KOMUNIKASI SOSIAL'),
	(93, 'AKTIF', 'B', 'B-14', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PEWARTAAN DAN EVANGELISASI LAIN-LAIN'),
	(94, 'AKTIF', 'C', 'C-01', 'BIDANG PELAYANAN KEMASYARAKATAN', 'BIDANG PELAYANAN KEMASYARAKATAN'),
	(95, 'AKTIF', 'C', 'C-02', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN PENGEMBANGAN SOSIAL EKONOMI'),
	(96, 'AKTIF', 'C', 'C-03', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN KESEHATAN'),
	(97, 'AKTIF', 'C', 'C-04', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN PENDIDIKAN'),
	(98, 'AKTIF', 'C', 'C-05', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN PANGRUKTILAYA'),
	(99, 'AKTIF', 'C', 'C-06', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN BERKAT SANTO YUSUF'),
	(100, 'AKTIF', 'C', 'C-07', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN HUBUNGAN ANTAR AGAMA DAN KEPERCAYAAN'),
	(101, 'AKTIF', 'C', 'C-08', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN KARYA KERASULAN KEMASYARAKATAN'),
	(102, 'AKTIF', 'C', 'C-09', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN KEUTUHAN CIPTAAN DAN LINGKUNGAN HIDUP'),
	(103, 'AKTIF', 'C', 'C-10', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN KEMASYARAKATAN LAIN-LAIN'),
	(104, 'AKTIF', 'D', 'D-01', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN'),
	(105, 'AKTIF', 'D', 'D-02', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'TIM PELAYANAN IBU-IBU PAROKI'),
	(106, 'AKTIF', 'D', 'D-03', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'TIM PELAYANAN PASTORAL KELUARGA PAROKI'),
	(107, 'AKTIF', 'D', 'D-04', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'TIM PELAYANAN KESENIAN'),
	(108, 'AKTIF', 'D', 'D-05', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'TIM PELAYANAN PERPUSTAKAAN'),
	(109, 'AKTIF', 'D', 'D-06', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'TIM PELAYANAN PAGUYUBAN DAN PERSAUDARAAN LAIN-LAIN'),
	(110, 'AKTIF', 'E', 'E-01', 'BIDANG RUMAH TANGGA', 'BIDANG RUMAH TANGGA'),
	(111, 'AKTIF', 'E', 'E-02', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN RUMAH TANGGA PAROKI'),
	(112, 'AKTIF', 'E', 'E-03', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN RUMAH TANGGA PASTORAN'),
	(113, 'AKTIF', 'E', 'E-04', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN KEAMANAN DAN PARKIR'),
	(114, 'AKTIF', 'E', 'E-05', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN LISTRIK DAN AUDIO VISUAL'),
	(115, 'AKTIF', 'E', 'E-06', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN PEMELIHARAAN DAN INVENTARIS'),
	(116, 'AKTIF', 'E', 'E-07', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN RUMAH TANGGA LAIN-LAIN'),
	(117, 'AKTIF', 'F', 'F-01', 'BIDANG PENELITIAN DAN PENGEMBANGAN', 'BIDANG PENELITIAN DAN PENGEMBANGAN'),
	(118, 'AKTIF', 'F', 'F-02', 'BIDANG PENELITIAN DAN PENGEMBANGAN', 'TIM PELAYANAN PENDATAAN'),
	(119, 'AKTIF', 'F', 'F-03', 'BIDANG PENELITIAN DAN PENGEMBANGAN', 'TIM PELAYANAN PENGEMBANGAN SDM'),
	(120, 'AKTIF', 'F', 'F-04', 'BIDANG PENELITIAN DAN PENGEMBANGAN', 'TIM PELAYANAN PROGRAMASI DAN MONEV'),
	(121, 'AKTIF', 'F', 'F-05', 'BIDANG PENELITIAN DAN PENGEMBANGAN', 'TIM PELAYANAN PENELITIAN DAN PENGEMBANGAN LAIN-LAIN'),
	(122, 'AKTIF', 'G', 'G-01', 'KEPANITIAAN', 'PANITIA PASKAH'),
	(123, 'AKTIF', 'G', 'G-02', 'KEPANITIAAN', 'PANITIA NATAL'),
	(124, 'AKTIF', 'G', 'G-03', 'KEPANITIAAN', 'PANITIA HUT PAROKI'),
	(125, 'AKTIF', 'G', 'G-04', 'KEPANITIAAN', 'PANITIA MISA DAN KEGIATAN IMLEK'),
	(126, 'AKTIF', 'G', 'G-05', 'KEPANITIAAN', 'PANITIA MISA DAN KEGIATAN MALAM 1 SURO'),
	(127, 'AKTIF', 'G', 'G-06', 'KEPANITIAAN', 'PANITIA MISA DAN KEGIATAN TAHUN BARU'),
	(128, 'AKTIF', 'G', 'G-07', 'KEPANITIAAN', 'PANITIA MISA DAN KEGIATAN NOVENA-DEVOSI'),
	(129, 'AKTIF', 'G', 'G-08', 'KEPANITIAAN', 'PANITIA HARI PANGAN SEDUNIA'),
	(130, 'AKTIF', 'G', 'G-09', 'KEPANITIAAN', 'PEMBEKALAN PENGURUS DEWAN PASTORAL PAROKI'),
	(131, 'AKTIF', 'G', 'G-10', 'KEPANITIAAN', 'PANITIA SAKRAMEN INISIASI'),
	(132, 'AKTIF', 'G', 'G-11', 'KEPANITIAAN', 'PANITIA LAIN-LAIN');
/*!40000 ALTER TABLE `kelompok_master` ENABLE KEYS */;

-- Dumping structure for table gsmf-monev.periksa_master
CREATE TABLE IF NOT EXISTS `periksa_master` (
  `perprm` int(11) NOT NULL AUTO_INCREMENT,
  `per_mst_dt` varchar(20) DEFAULT NULL,
  `per_mst_nobuk` varchar(20) DEFAULT NULL,
  `per_mst_sts` varchar(20) DEFAULT NULL,
  `per_mst_tgl` date DEFAULT NULL,
  `per_mst_pst` varchar(20) DEFAULT NULL,
  `per_mst_ket` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`perprm`),
  KEY `per_mst_dt_per_mst_nobuk` (`per_mst_dt`,`per_mst_nobuk`),
  KEY `per_mst_nobuk_per_mst_sts` (`per_mst_nobuk`,`per_mst_sts`),
  KEY `per_mst_tgl` (`per_mst_tgl`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table gsmf-monev.periksa_master: ~0 rows (approximately)
/*!40000 ALTER TABLE `periksa_master` DISABLE KEYS */;
INSERT INTO `periksa_master` (`perprm`, `per_mst_dt`, `per_mst_nobuk`, `per_mst_sts`, `per_mst_tgl`, `per_mst_pst`, `per_mst_ket`) VALUES
	(1, 'VER', 'AGR-20210407-48937', 'SETUJU', '2021-04-07', 'GSU', ''),
	(2, 'VER', 'AGR-20210407-72239', 'TOLAK', '2021-04-07', 'GSU', 'tolak... ga ada duit di kas');
/*!40000 ALTER TABLE `periksa_master` ENABLE KEYS */;

-- Dumping structure for table gsmf-monev.peserta_master
CREATE TABLE IF NOT EXISTS `peserta_master` (
  `pstprm` int(11) NOT NULL AUTO_INCREMENT,
  `pst_mst_sts` varchar(20) DEFAULT NULL,
  `pst_mst_kode` varchar(20) DEFAULT NULL,
  `pst_mst_kel` varchar(20) DEFAULT NULL,
  `pst_mst_hak` varchar(20) DEFAULT NULL,
  `pst_mst_nm` varchar(2000) DEFAULT NULL,
  `pst_mst_pswd` varchar(2000) DEFAULT NULL,
  `pst_mst_lock` int(11) DEFAULT NULL,
  PRIMARY KEY (`pstprm`),
  UNIQUE KEY `pst_mst_kode_pst_mst_sts` (`pst_mst_sts`,`pst_mst_kode`),
  UNIQUE KEY `pst_mst_kode` (`pst_mst_kode`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table gsmf-monev.peserta_master: ~2 rows (approximately)
/*!40000 ALTER TABLE `peserta_master` DISABLE KEYS */;
INSERT INTO `peserta_master` (`pstprm`, `pst_mst_sts`, `pst_mst_kode`, `pst_mst_kel`, `pst_mst_hak`, `pst_mst_nm`, `pst_mst_pswd`, `pst_mst_lock`) VALUES
	(10, 'AKTIF', 'GSU', 'F-01', 'PEMILIK', 'GREGORIUSSATRIOUTOMO', '68ba07abf0d370630620ea43c68fabbd', 1);
/*!40000 ALTER TABLE `peserta_master` ENABLE KEYS */;

-- Dumping structure for table gsmf-monev.rekening_master
CREATE TABLE IF NOT EXISTS `rekening_master` (
  `rekprm` int(11) NOT NULL AUTO_INCREMENT,
  `rek_mst_sts` varchar(20) DEFAULT NULL,
  `rek_mst_kel` varchar(20) DEFAULT NULL,
  `rek_mst_gol` varchar(20) DEFAULT NULL,
  `rek_mst_sub_gol` varchar(20) DEFAULT NULL,
  `rek_mst_kode` varchar(20) DEFAULT NULL,
  `rek_mst_sub_kode` varchar(20) DEFAULT NULL,
  `rek_mst_ket_sub_kode` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`rekprm`),
  UNIQUE KEY `komplit` (`rek_mst_sts`,`rek_mst_kel`,`rek_mst_gol`,`rek_mst_sub_gol`,`rek_mst_kode`,`rek_mst_sub_kode`),
  UNIQUE KEY `rek_mst_sub_kode` (`rek_mst_sub_kode`)
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table gsmf-monev.rekening_master: ~73 rows (approximately)
/*!40000 ALTER TABLE `rekening_master` DISABLE KEYS */;
INSERT INTO `rekening_master` (`rekprm`, `rek_mst_sts`, `rek_mst_kel`, `rek_mst_gol`, `rek_mst_sub_gol`, `rek_mst_kode`, `rek_mst_sub_kode`, `rek_mst_ket_sub_kode`) VALUES
	(1, 'AKTIF', 'NERACA', 'ASET', 'ASETLANCAR', 'SETARAKAS', '1111-01', 'KAS'),
	(2, 'AKTIF', 'NERACA', 'ASET', 'ASETLANCAR', 'SETARAKAS', '1111-02', 'BANK'),
	(3, 'AKTIF', 'NERACA', 'ASET', 'ASETLANCAR', 'SETARAKAS', '1111-03', 'DEPOSITO'),
	(4, 'AKTIF', 'NERACA', 'ASET', 'ASETLANCAR', 'SETARAKAS', '1111-04', 'GIRO'),
	(5, 'AKTIF', 'NERACA', 'ASET', 'ASETLANCAR', 'PIUTANG', '1112-01', 'LEMBAGA'),
	(6, 'AKTIF', 'NERACA', 'ASET', 'ASETLANCAR', 'PIUTANG', '1112-02', 'PERORANGAN'),
	(7, 'AKTIF', 'NERACA', 'ASET', 'ASETLANCAR', 'PIUTANG', '1112-03', 'BIDANG'),
	(8, 'AKTIF', 'NERACA', 'ASET', 'ASETLANCAR', 'PIUTANG', '1112-04', 'TIMPELAYANAN'),
	(9, 'AKTIF', 'NERACA', 'ASET', 'ASETLANCAR', 'PERSEDIAAN', '1113-01', 'PERSEDIAAN'),
	(10, 'AKTIF', 'NERACA', 'ASET', 'ASETLANCAR', 'PERLENGKAPAN', '1113-02', 'HABISPAKAI'),
	(11, 'AKTIF', 'NERACA', 'ASET', 'ASETTETAP', 'BERGERAK', '1121-01', 'TANAH'),
	(12, 'AKTIF', 'NERACA', 'ASET', 'ASETTETAP', 'BERGERAK', '1121-02', 'BANGUNAN'),
	(13, 'AKTIF', 'NERACA', 'ASET', 'ASETTETAP', 'BERGERAK', '1121-03', 'SUSUT'),
	(14, 'AKTIF', 'NERACA', 'ASET', 'ASETTETAP', 'TIDAKBERGERAK', '1122-01', 'KENDARAAN'),
	(15, 'AKTIF', 'NERACA', 'ASET', 'ASETTETAP', 'TIDAKBERGERAK', '1122-02', 'SUSUT'),
	(16, 'AKTIF', 'NERACA', 'ASET', 'ASETLAIN', 'LAIN', '1131-01', 'LAIN'),
	(17, 'AKTIF', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN', 'JANGKAPANJANG', '1211-01', 'LEMBAGA'),
	(18, 'AKTIF', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN', 'JANGKAPANJANG', '1211-02', 'PERORANGAN'),
	(19, 'AKTIF', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN', 'JANGKAPENDEK', '1212-01', 'LEMBAGA'),
	(20, 'AKTIF', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN', 'JANGKAPENDEK', '1212-02', 'PERORANGAN'),
	(21, 'AKTIF', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN', 'KHUSUS', '1213-01', 'LEMBAGA'),
	(22, 'AKTIF', 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN', 'KHUSUS', '1213-02', 'PERORANGAN'),
	(23, 'AKTIF', 'NERACA', 'ASET BERSIH', 'TIDAKTERIKAT', 'TIDAKTERIKAT', '1311-01', 'AKUMULASI'),
	(24, 'AKTIF', 'NERACA', 'ASET BERSIH', 'TERIKATSEMENTARA', 'NONPEMBANGUNAN', '1321-01', 'AKUMULASI'),
	(25, 'AKTIF', 'NERACA', 'ASET BERSIH', 'TERIKATSEMENTARA', 'PEMBANGUNAN', '1322-01', 'AKUMULASI'),
	(26, 'AKTIF', 'NERACA', 'ASET BERSIH', 'TERIKATSEMENTARA', 'UKSP', '1323-01', 'AKUMULASI'),
	(27, 'AKTIF', 'ANGGARAN', 'ABTT', 'PENDAPATAN', 'KOLEKTE', '2111-01', 'MISAUMUM'),
	(28, 'AKTIF', 'ANGGARAN', 'ABTT', 'PENDAPATAN', 'KOLEKTE', '2111-02', 'MISAKHUSUS'),
	(29, 'AKTIF', 'ANGGARAN', 'ABTT', 'PENDAPATAN', 'BANTUAN', '2112-01', 'LEMBAGA'),
	(30, 'AKTIF', 'ANGGARAN', 'ABTT', 'PENDAPATAN', 'BANTUAN', '2112-02', 'PERORANGAN'),
	(31, 'AKTIF', 'ANGGARAN', 'ABTT', 'PENDAPATAN', 'UMUM', '2113-01', 'BUNGABANK'),
	(32, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'PROGRAM', '2121-01', 'BIDANG'),
	(33, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'PROGRAM', '2121-02', 'TIMPELAYANAN'),
	(34, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-01', 'KARYAWAN'),
	(35, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-02', 'GEREJA'),
	(36, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-03', 'RUMAHTANGGA'),
	(37, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-04', 'KEAMANAN'),
	(38, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-05', 'ADMINISTRASI'),
	(39, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-06', 'DEVOSIONALIA'),
	(40, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-07', 'AULAPAROKI'),
	(41, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-08', 'DEWANPASTORAL'),
	(42, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-09', 'PENYUSUTAN'),
	(43, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-10', 'PAJAKBUNGABANK'),
	(44, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-11', 'ADMINISTRASIBANK'),
	(45, 'AKTIF', 'ANGGARAN', 'ABTT', 'BIAYA', 'RUTIN', '2122-12', 'PAJAK'),
	(46, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'BANTUAN', '2211-01', 'PENDIDIKAN'),
	(47, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'BANTUAN', '2211-02', 'KESEHATAN'),
	(48, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'BANTUAN', '2211-03', 'SEMINARI'),
	(49, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'UMUM', '2212-01', 'DANAPAPAMISKIN'),
	(50, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'UMUM', '2212-02', 'APP'),
	(51, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'UMUM', '2212-03', 'PANGRUKTILAYA'),
	(52, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'UMUM', '2212-04', 'BKSY'),
	(53, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'UMUM', '2212-05', 'PENDINGCOFFEE'),
	(54, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'PENDAPATAN', 'UMUM', '2212-06', 'BUNGABANK'),
	(55, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'UMUM', '2213-01', 'DANAPAPAMISKIN'),
	(56, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'UMUM', '2213-02', 'PENDIDIKAN'),
	(57, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'UMUM', '2213-03', 'KESEHATAN'),
	(58, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'UMUM', '2213-04', 'SEMINARI'),
	(59, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'UMUM', '2213-05', 'APP'),
	(60, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'UMUM', '2213-06', 'PANGRUKTILAYA'),
	(61, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'UMUM', '2213-07', 'BKSY'),
	(62, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'UMUM', '2213-08', 'PENDINGCOFFEE'),
	(63, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'RUTIN', '2214-01', 'PAJAKBUNGABANK'),
	(64, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'RUTIN', '2214-02', 'ADMINISTRASIBANK'),
	(65, 'AKTIF', 'ANGGARAN', 'ABTS-NP', 'BIAYA', 'RUTIN', '2214-03', 'PAJAK'),
	(66, 'AKTIF', 'ANGGARAN', 'ABTS-P', 'PENDAPATAN', 'KOLEKTE', '2311-01', 'MISAUMUM'),
	(67, 'AKTIF', 'ANGGARAN', 'ABTS-P', 'PENDAPATAN', 'KOLEKTE', '2311-02', 'MISAKHUSUS'),
	(68, 'AKTIF', 'ANGGARAN', 'ABTS-P', 'PENDAPATAN', 'BANTUAN', '2312-01', 'LEMBAGA'),
	(69, 'AKTIF', 'ANGGARAN', 'ABTS-P', 'PENDAPATAN', 'BANTUAN', '2312-02', 'PERORANGAN'),
	(70, 'AKTIF', 'ANGGARAN', 'ABTS-P', 'PENDAPATAN', 'UMUM', '2313-01', 'BUNGABANK'),
	(71, 'AKTIF', 'ANGGARAN', 'ABTS-P', 'BIAYA', 'RUTIN', '2321-01', 'PAJAKBUNGABANK'),
	(72, 'AKTIF', 'ANGGARAN', 'ABTS-P', 'BIAYA', 'RUTIN', '2321-02', 'ADMINISTRASIBANK'),
	(73, 'AKTIF', 'ANGGARAN', 'ABTS-P', 'BIAYA', 'RUTIN', '2321-03', 'PAJAK');
/*!40000 ALTER TABLE `rekening_master` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
