-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.17-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table aturduit.cek_detail: ~2 rows (approximately)
/*!40000 ALTER TABLE `cek_detail` DISABLE KEYS */;
REPLACE INTO `cek_detail` (`cekprm`, `cek_det_lock`, `cek_det_dt`, `cek_det_nobuk`, `cek_det_tgl`, `cek_det_sts`) VALUES
	(182, 0, 'AGR', 'AGR-20210324-99229', '2021-03-24', NULL),
	(183, 0, 'AGR', 'AGR-20210324-99229', '2021-03-24', 'TOLAK');
/*!40000 ALTER TABLE `cek_detail` ENABLE KEYS */;

-- Dumping data for table aturduit.cek_master: ~1 rows (approximately)
/*!40000 ALTER TABLE `cek_master` DISABLE KEYS */;
REPLACE INTO `cek_master` (`cekprm`, `cek_mst_lock`, `cek_mst_dt`, `cek_mst_nobuk`, `cek_mst_sts`, `cek_mst_tgl`, `cek_mst_pgn`, `cek_mst_ket`) VALUES
	(111, 0, 'AGR', 'AGR-20210324-99229', 'TOLAK', '2021-03-24', 'GSU', 'GA JADI STUJU... TOLAK AJA DEH...');
/*!40000 ALTER TABLE `cek_master` ENABLE KEYS */;

-- Dumping data for table aturduit.hutang_detail: ~4 rows (approximately)
/*!40000 ALTER TABLE `hutang_detail` DISABLE KEYS */;
REPLACE INTO `hutang_detail` (`hutprm`, `hut_det_lock`, `hut_det_dt`, `hut_det_nobuk`, `hut_det_rek`, `hut_det_rnc`) VALUES
	(182, 0, 'AGR', 'AGR-20210324-99229', '700.01', 250000),
	(183, 0, 'AGR', 'AGR-20210324-99229', '700.02', 150000),
	(184, 0, 'AGR', 'AGR-20210324-99229', '700.03', 25000),
	(185, 0, 'AGR', 'AGR-20210324-99229', '700.05', 100000);
/*!40000 ALTER TABLE `hutang_detail` ENABLE KEYS */;

-- Dumping data for table aturduit.hutang_master: ~1 rows (approximately)
/*!40000 ALTER TABLE `hutang_master` DISABLE KEYS */;
REPLACE INTO `hutang_master` (`hutprm`, `hut_mst_lock`, `hut_mst_dt`, `hut_mst_nobuk`, `hut_mst_sts`, `hut_mst_tgl`, `hut_mst_tglrnc`, `hut_mst_pgn`, `hut_mst_rnc`, `hut_mst_ttl`, `hut_mst_ket`) VALUES
	(111, 0, 'AGR', 'AGR-20210324-99229', 'TOLAK', '2021-03-24', '2021-05-31', 'GSU', 525000, 0, 'MAKAN MAKAN');
/*!40000 ALTER TABLE `hutang_master` ENABLE KEYS */;

-- Dumping data for table aturduit.jurnal: ~0 rows (approximately)
/*!40000 ALTER TABLE `jurnal` DISABLE KEYS */;
/*!40000 ALTER TABLE `jurnal` ENABLE KEYS */;

-- Dumping data for table aturduit.kelompok_master: ~55 rows (approximately)
/*!40000 ALTER TABLE `kelompok_master` DISABLE KEYS */;
REPLACE INTO `kelompok_master` (`kelprm`, `kel_mst_kode`, `kel_mst_subkode`, `kel_mst_sts`, `kel_mst_ket`, `kel_mst_subket`) VALUES
	(24, '5-01', '5-01-00', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'BIDANG LITURGI DAN PERIBADATAN'),
	(25, '5-02', '5-02-00', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'BIDANG PEWARTAAN DAN EVANGELISASI'),
	(26, '5-03', '5-03-00', 'AKTIF', 'BIDANG PELAYANAN KEMASYARAKATAN', 'BIDANG PELAYANAN KEMASYARAKATAN'),
	(27, '5-04', '5-04-00', 'AKTIF', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN'),
	(28, '5-05', '5-05-00', 'AKTIF', 'BIDANG RUMAH TANGGA', 'BIDANG RUMAH TANGGA'),
	(29, '5-06', '5-06-00', 'AKTIF', 'BIDANG PENELITIAN DAN PENGEMBANGAN', 'BIDANG PENELITIAN DAN PENGEMBANGAN'),
	(30, '5-07', '5-07-00', 'AKTIF', 'KEPANITIAAN DAN PROGRAM DEWAN', 'KEPANITIAAN DAN PROGRAM DEWAN LAINNYA'),
	(35, '5-01', '5-01-01', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN TATA PERAYAAN DAN PERIBADATAN'),
	(36, '5-01', '5-01-02', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PRODIAKON'),
	(39, '5-01', '5-01-03', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PUTRA PUTRI ALTAR'),
	(40, '5-01', '5-01-04', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PADUAN SUARA'),
	(41, '5-01', '5-01-05', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN LEKTOR'),
	(42, '5-01', '5-01-06', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PEMAZMUR'),
	(45, '5-01', '5-01-07', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PEMUSIK'),
	(46, '5-01', '5-01-08', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN DIRIGEN'),
	(47, '5-01', '5-01-09', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN PARAMENTA'),
	(49, '5-01', '5-01-10', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN TATA ALTAR'),
	(50, '5-01', '5-01-11', 'AKTIF', 'BIDANG LITURGI DAN PERIBADATAN', 'TIM PELAYANAN LITURGI DAN PERIBADATAN LAIN-LAIN'),
	(52, '5-02', '5-02-01', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN EVANGELISASI'),
	(53, '5-02', '5-02-02', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN SAKRAMEN INISIASI'),
	(54, '5-02', '5-02-03', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN KATEKIS'),
	(55, '5-02', '5-02-04', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN KERASULAN KITAB SUCI'),
	(56, '5-02', '5-02-05', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN USIA DINI'),
	(57, '5-02', '5-02-06', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN ANAK'),
	(58, '5-02', '5-02-07', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN REMAJA'),
	(59, '5-02', '5-02-08', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN ORANG MUDA'),
	(60, '5-02', '5-02-09', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN ORANG DEWASA'),
	(61, '5-02', '5-02-10', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PENDAMPINGAN IMAN USIA LANJUT'),
	(62, '5-02', '5-02-11', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PROMOSI PANGGILAN'),
	(63, '5-02', '5-02-12', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN KOMUNIKASI SOSIAL'),
	(64, '5-02', '5-02-13', 'AKTIF', 'BIDANG PEWARTAAN DAN EVANGELISASI', 'TIM PELAYANAN PEWARTAAN DAN EVANGELISASI LAIN-LAIN'),
	(66, '5-03', '5-03-01', 'AKTIF', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN PSE'),
	(67, '5-03', '5-03-02', 'AKTIF', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN KESEHATAN'),
	(68, '5-03', '5-03-03', 'AKTIF', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN PENDIDIKAN'),
	(69, '5-03', '5-03-04', 'AKTIF', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN PANGRUKTILAYA'),
	(70, '5-03', '5-03-05', 'AKTIF', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN BKSY'),
	(71, '5-03', '5-03-06', 'AKTIF', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN HUBUNGAN ANTAR AGAMA DAN KEPERCAYAAN'),
	(72, '5-03', '5-03-07', 'AKTIF', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN KARYA KERASULAN KEMASYARAKATAN'),
	(73, '5-03', '5-03-08', 'AKTIF', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN KEUTUHAN CIPTAAN DAN LINGKUNGAN HIDUP'),
	(74, '5-03', '5-03-09', 'AKTIF', 'BIDANG PELAYANAN KEMASYARAKATAN', 'TIM PELAYANAN KEMASYARAKATAN LAIN-LAIN'),
	(76, '5-04', '5-04-01', 'AKTIF', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'TIM PELAYANAN IBU-IBU PAROKI'),
	(77, '5-04', '5-04-02', 'AKTIF', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'TIM PELAYANAN PASTORAL KELUARGA PAROKI'),
	(78, '5-04', '5-04-03', 'AKTIF', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'TIM PELAYANAN KESENIAN'),
	(79, '5-04', '5-04-04', 'AKTIF', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'TIM PELAYANAN PERPUSTAKAAN'),
	(80, '5-04', '5-04-05', 'AKTIF', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', 'TIM PELAYANAN PAGUYUBAN DAN PERSAUDARAAN LAIN-LAIN'),
	(81, '5-05', '5-05-01', 'AKTIF', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN RUMAH TANGGA PAROKI'),
	(82, '5-05', '5-05-02', 'AKTIF', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN RUMAH TANGGA PASTORAN'),
	(83, '5-05', '5-05-03', 'AKTIF', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN KEAMANAN DAN PARKIR'),
	(84, '5-05', '5-05-04', 'AKTIF', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN LISTRIK DAN AUDIO VISUAL'),
	(85, '5-05', '5-05-05', 'AKTIF', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN PEMELIHARAAN DAN INVENTARIS'),
	(86, '5-05', '5-05-06', 'AKTIF', 'BIDANG RUMAH TANGGA', 'TIM PELAYANAN RUMAH TANGGA LAIN-LAIN'),
	(87, '5-06', '5-06-01', 'AKTIF', 'BIDANG PENELITIAN DAN PENGEMBANGAN', 'TIM PELAYANAN PENDATAAN'),
	(88, '5-06', '5-06-02', 'AKTIF', 'BIDANG PENELITIAN DAN PENGEMBANGAN', 'TIM PELAYANAN PENGEMBANGAN SDM'),
	(89, '5-06', '5-06-03', 'AKTIF', 'BIDANG PENELITIAN DAN PENGEMBANGAN', 'TIM PELAYANAN PROGRAMASI DAN MONEV'),
	(90, '5-06', '5-06-04', 'AKTIF', 'BIDANG PENELITIAN DAN PENGEMBANGAN', 'TIM PELAYANAN PENELITIAN DAN PENGEMBANGAN LAIN-LAIN');
/*!40000 ALTER TABLE `kelompok_master` ENABLE KEYS */;

-- Dumping data for table aturduit.peserta_master: ~1 rows (approximately)
/*!40000 ALTER TABLE `peserta_master` DISABLE KEYS */;
REPLACE INTO `peserta_master` (`pstprm`, `pst_mst_kode`, `pst_mst_kel`, `pst_mst_hak`, `pst_mst_sts`, `pst_mst_nm`, `pst_mst_pswd`) VALUES
	(15, 'GSU', '5-06-00', 'PEMILIK', 'AKTIF', 'GREGORIUSSATRIOUTOMO', 'a906449d5769fa7361d7ecc6aa3f6d28');
/*!40000 ALTER TABLE `peserta_master` ENABLE KEYS */;

-- Dumping data for table aturduit.rekening_master: ~58 rows (approximately)
/*!40000 ALTER TABLE `rekening_master` DISABLE KEYS */;
REPLACE INTO `rekening_master` (`rekprm`, `rek_mst_kel`, `rek_mst_gol`, `rek_mst_sub_gol`, `rek_mst_kode`, `rek_mst_sub_kode`, `rek_mst_sts`, `rek_mst_ket_gol`, `rek_mst_ket_sub_gol`, `rek_mst_ket_kode`, `rek_mst_ket_sub_kode`, `rek_mst_sdawl`, `rek_mst_mutdeb`, `rek_mst_mutkre`, `rek_mst_sdakh`) VALUES
	(49, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-1', 'ASET-A-1-01', 'AKTIF', 'ASET', 'ASET LANCAR', 'KAS', 'TIDAK TERIKAT - PROGRAM DAN KEGIATAN RUTIN', NULL, NULL, NULL, NULL),
	(50, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-1', 'ASET-A-1-02', 'AKTIF', 'ASET', 'ASET LANCAR', 'KAS', 'TERIKAT SEMENTARA NON PEMBANGUNAN', NULL, NULL, NULL, NULL),
	(51, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-1', 'ASET-A-1-03', 'AKTIF', 'ASET', 'ASET LANCAR', 'KAS', 'TERIKAT SEMENTARA PEMBANGUNAN', NULL, NULL, NULL, NULL),
	(52, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-2', 'ASET-A-2-01', 'AKTIF', 'ASET', 'ASET LANCAR', 'TABUNGAN DAN GIRO', 'TIDAK TERIKAT - PROGRAM DAN KEGIATAN RUTIN', NULL, NULL, NULL, NULL),
	(53, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-2', 'ASET-A-2-02', 'AKTIF', 'ASET', 'ASET LANCAR', 'TABUNGAN DAN GIRO', 'TERIKAT SEMENTARA NON PEMBANGUNAN', NULL, NULL, NULL, NULL),
	(54, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-2', 'ASET-A-2-03', 'AKTIF', 'ASET', 'ASET LANCAR', 'TABUNGAN DAN GIRO', 'TERIKAT SEMENTARA PEMBANGUNAN', NULL, NULL, NULL, NULL),
	(55, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-3', 'ASET-A-3-01', 'AKTIF', 'ASET', 'ASET LANCAR', 'DEPOSITO', 'TIDAK TERIKAT - PROGRAM DAN KEGIATAN RUTIN', NULL, NULL, NULL, NULL),
	(56, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-3', 'ASET-A-3-02', 'AKTIF', 'ASET', 'ASET LANCAR', 'DEPOSITO', 'TERIKAT SEMENTARA NON PEMBANGUNAN', NULL, NULL, NULL, NULL),
	(57, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-3', 'ASET-A-3-03', 'AKTIF', 'ASET', 'ASET LANCAR', 'DEPOSITO', 'TERIKAT SEMENTARA PEMBANGUNAN', NULL, NULL, NULL, NULL),
	(58, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-4', 'ASET-A-4-01', 'AKTIF', 'ASET', 'ASET LANCAR', 'PIUTANG', 'PIUTANG', NULL, NULL, NULL, NULL),
	(59, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-01', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'PEMBELIAN', NULL, NULL, NULL, NULL),
	(60, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-02', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'SEKERTARIAT', NULL, NULL, NULL, NULL),
	(61, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-03', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'BIDANG LITURGI DAN PERIBADATAN', NULL, NULL, NULL, NULL),
	(62, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-04', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'BIDANG PEWARTAAN DAN EVANGELISASI', NULL, NULL, NULL, NULL),
	(63, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-05', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'BIDANG PELAYANAN KEMASYARAKATAN', NULL, NULL, NULL, NULL),
	(64, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-06', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'BIDANG PAGUYUBAN DAN PERSAUDARAAN', NULL, NULL, NULL, NULL),
	(65, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-07', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'BIDANG RUMAH TANGGA', NULL, NULL, NULL, NULL),
	(66, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-08', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'BIDANG PENELITIAN DAN PENGEMBANGAN', NULL, NULL, NULL, NULL),
	(67, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-09', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'KEPANITIAAN DAN PROGRAM DEWAN LAINNYA', NULL, NULL, NULL, NULL),
	(68, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-10', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'PROGRAM VISIONER', NULL, NULL, NULL, NULL),
	(69, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-5', 'ASET-A-5-11', 'AKTIF', 'ASET', 'ASET LANCAR', 'UANG MUKA', 'PEMBANGUNAN', NULL, NULL, NULL, NULL),
	(70, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-6', 'ASET-A-6-01', 'AKTIF', 'ASET', 'ASET LANCAR', 'DIBAYAR DIMUKA', 'ASURANSI', NULL, NULL, NULL, NULL),
	(71, 'NERACA', 'ASET', 'ASET-A', 'ASET-A-7', 'ASET-A-7-01', 'AKTIF', 'ASET', 'ASET LANCAR', 'PERSEDIAAN', 'PERSEDIAAN BARANG DEVOSI', NULL, NULL, NULL, NULL),
	(72, 'NERACA', 'ASET', 'ASET-B', 'ASET-B-1', 'ASET-B-1-01', 'AKTIF', 'ASET', 'ASET TETAP', 'INVENTARIS', 'INVENTARIS', NULL, NULL, NULL, NULL),
	(73, 'NERACA', 'ASET', 'ASET-B', 'ASET-B-1', 'ASET-B-1-02', 'AKTIF', 'ASET', 'ASET TETAP', 'INVENTARIS', 'AKUMULASI PENYUSUTAN', NULL, NULL, NULL, NULL),
	(74, 'NERACA', 'ASET', 'ASET-C', 'ASET-C-1', 'ASET-C-1-01', 'AKTIF', 'ASET', 'ASET LAINNYA', 'ASET LAINNYA', 'BANGUNAN DALAM PROSES', NULL, NULL, NULL, NULL),
	(75, 'NERACA', 'ASET', 'ASET-D', 'ASET-D-1', 'ASET-D-1-01', 'AKTIF', 'ASET', 'AYAT SILANG', 'AYAT SILANG', 'AYAT SILANG', NULL, NULL, NULL, NULL),
	(76, 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN-A', 'KEWAJIBAN-A-1', 'KEWAJIBAN-A-1-01', 'AKTIF', 'KEWAJIBAN', 'KEWAJIBAN', 'KEWAJIBAN', 'JANGKA PENDEK', NULL, NULL, NULL, NULL),
	(77, 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN-A', 'KEWAJIBAN-A-1', 'KEWAJIBAN-A-1-02', 'AKTIF', 'KEWAJIBAN', 'KEWAJIBAN', 'KEWAJIBAN', 'KHUSUS PAROKI', NULL, NULL, NULL, NULL),
	(78, 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN-A', 'KEWAJIBAN-A-1', 'KEWAJIBAN-A-1-03', 'AKTIF', 'KEWAJIBAN', 'KEWAJIBAN', 'KEWAJIBAN', 'LAIN-LAIN', NULL, NULL, NULL, NULL),
	(79, 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN-A', 'KEWAJIBAN-A-1', 'KEWAJIBAN-A-1-04', 'AKTIF', 'KEWAJIBAN', 'KEWAJIBAN', 'KEWAJIBAN', 'BEBAN DAN PAJAK', NULL, NULL, NULL, NULL),
	(80, 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN-A', 'KEWAJIBAN-A-1', 'KEWAJIBAN-A-1-05', 'AKTIF', 'KEWAJIBAN', 'KEWAJIBAN', 'KEWAJIBAN', 'JANGKA PANJANG', NULL, NULL, NULL, NULL),
	(81, 'NERACA', 'KEWAJIBAN', 'KEWAJIBAN-A', 'KEWAJIBAN-A-1', 'KEWAJIBAN-A-1-06', 'AKTIF', 'KEWAJIBAN', 'KEWAJIBAN', 'KEWAJIBAN', 'DANA CINTA KASIH', NULL, NULL, NULL, NULL),
	(82, 'NERACA', 'ASET BERSIH', 'ASET BERSIH-A', 'ASET BERSIH-A-1', 'ASET BERSIH-A-1-01', 'AKTIF', 'ASET BERSIH', 'ASET BERSIH', 'ASET BERSIH', 'TIDAK TERIKAT', NULL, NULL, NULL, NULL),
	(83, 'NERACA', 'ASET BERSIH', 'ASET BERSIH-A', 'ASET BERSIH-A-1', 'ASET BERSIH-A-1-02', 'AKTIF', 'ASET BERSIH', 'ASET BERSIH', 'ASET BERSIH', 'TERIKAT SEMENTARA', NULL, NULL, NULL, NULL),
	(86, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-1', 'ABTT-A-1-01', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'KOLEKTE DAN PERSEMBAHAN', 'UMUM DAN PERSEMBAHAN BULANAN', NULL, NULL, NULL, NULL),
	(87, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-1', 'ABTT-A-1-02', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'KOLEKTE DAN PERSEMBAHAN', 'MISA DAN PERSEMBAHAN PASKAH', NULL, NULL, NULL, NULL),
	(88, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-1', 'ABTT-A-1-03', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'KOLEKTE DAN PERSEMBAHAN', 'MISA DAN PERSEMBAHAN NATAL', NULL, NULL, NULL, NULL),
	(89, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-1', 'ABTT-A-1-04', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'KOLEKTE DAN PERSEMBAHAN', 'NOVENA DAN DEVOSI', NULL, NULL, NULL, NULL),
	(90, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-1', 'ABTT-A-1-05', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'KOLEKTE DAN PERSEMBAHAN', 'MISA JUMAT PERTAMA', NULL, NULL, NULL, NULL),
	(91, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-1', 'ABTT-A-1-06', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'KOLEKTE DAN PERSEMBAHAN', 'MISA SABTU IMAM', NULL, NULL, NULL, NULL),
	(92, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-1', 'ABTT-A-1-07', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'KOLEKTE DAN PERSEMBAHAN', 'MISA HARI KENAIKAN TUHAN', NULL, NULL, NULL, NULL),
	(93, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-1', 'ABTT-A-1-08', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'KOLEKTE DAN PERSEMBAHAN', 'MISA LAINNYA', NULL, NULL, NULL, NULL),
	(94, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-2', 'ABTT-A-2-01', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN UMAT', 'BANTUAN PERKAWINAN', NULL, NULL, NULL, NULL),
	(95, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-2', 'ABTT-A-2-02', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN UMAT', 'PEMAKAIAN GEREJA', NULL, NULL, NULL, NULL),
	(96, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-2', 'ABTT-A-2-03', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN UMAT', 'PEMAKAIAN AULA PAROKI', NULL, NULL, NULL, NULL),
	(97, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-2', 'ABTT-A-2-04', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN UMAT', 'CETAK LEMBARAN MISA', NULL, NULL, NULL, NULL),
	(98, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-2', 'ABTT-A-2-05', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN UMAT', 'PROGRAM PAROKI', NULL, NULL, NULL, NULL),
	(99, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-2', 'ABTT-A-2-06', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN UMAT', 'PARKIR', NULL, NULL, NULL, NULL),
	(100, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-2', 'ABTT-A-2-07', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN UMAT', 'LAIN-LAIN', NULL, NULL, NULL, NULL),
	(101, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-3', 'ABTT-A-3-01', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN DEVOSIONALIA', 'BANTUAN BARANG DEVOSI', NULL, NULL, NULL, NULL),
	(102, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-3', 'ABTT-A-3-02', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN DEVOSIONALIA', 'LILIN DEVOSI', NULL, NULL, NULL, NULL),
	(103, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-3', 'ABTT-A-3-03', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN DEVOSIONALIA', 'BUKU PANDUAN MISA', NULL, NULL, NULL, NULL),
	(104, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-3', 'ABTT-A-3-04', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN DEVOSIONALIA', 'LAIN-LAIN', NULL, NULL, NULL, NULL),
	(105, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-4', 'ABTT-A-4-01', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN LEMBAGA', 'PROGRAM DAN KEGIATAN RUTIN KAS', NULL, NULL, NULL, NULL),
	(106, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-4', 'ABTT-A-4-02', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN LEMBAGA', 'PROGRAM VISIONER KAS', NULL, NULL, NULL, NULL),
	(107, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-4', 'ABTT-A-4-03', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN LEMBAGA', 'LAINNYA KAS', NULL, NULL, NULL, NULL),
	(108, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-4', 'ABTT-A-4-04', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BANTUAN LEMBAGA', 'BANTUAN LEMBAGA NON KAS', NULL, NULL, NULL, NULL),
	(109, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-5', 'ABTT-A-5-01', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BUNGA BANK', 'BUNGA BANK', NULL, NULL, NULL, NULL),
	(110, 'ANGGARAN', 'ABTT', 'ABTT-A', 'ABTT-A-5', 'ABTT-A-5-02', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'PENERIMAAN', 'BUNGA BANK', 'BUNGA BANK DANA CINTA KASIH', NULL, NULL, NULL, NULL),
	(111, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-01', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'BIDANG LITURGI DAN PERIBADATAN', NULL, NULL, NULL, NULL),
	(112, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-02', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN TATA PERAYAAN DAN PERIBADATAN', NULL, NULL, NULL, NULL),
	(113, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-03', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN PRODIAKON', NULL, NULL, NULL, NULL),
	(114, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-04', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN PUTRA-PUTRI ALTAR', NULL, NULL, NULL, NULL),
	(115, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-05', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN PADUAN SUARA', NULL, NULL, NULL, NULL),
	(116, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-06', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN LEKTOR', NULL, NULL, NULL, NULL),
	(117, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-07', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN PEMAZMUR', NULL, NULL, NULL, NULL),
	(118, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-08', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN PEMUSIK', NULL, NULL, NULL, NULL),
	(119, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-09', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN DIRIGEN', NULL, NULL, NULL, NULL),
	(120, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-10', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN PARAMENTA', NULL, NULL, NULL, NULL),
	(121, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-11', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN TATA ALTAR', NULL, NULL, NULL, NULL),
	(122, 'ANGGARAN', 'ABTT', 'ABTT-B', 'ABTT-B-1', 'ABTT-B-1-12', 'AKTIF', 'ASET BERSIH TIDAK TERIKAT', 'BEBAN', 'PROGRAM', 'TIM PELAYANAN LITURGI DAN PERIBADATAN LAIN-LAIN', NULL, NULL, NULL, NULL);
/*!40000 ALTER TABLE `rekening_master` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
